export const STATIC_DATA = {
  HOUSES: {
    atreides: {
      name: "House Atreides",
      color: "house-atreides",
      bonus: "leadership",
      description: "+25% XP gain, +15% unit effectiveness, +10% territory income",
      startingBonus: { solari: 1000, xp: 300, water: 100 }, // Added water for balance
    },
    harkonnen: {
      name: "House Harkonnen",
      color: "house-harkonnen",
      bonus: "brutality",
      description: "+30% attack damage, +20% resource extraction, +15% enemy defeat rewards",
      startingBonus: { plasteel: 200, attack: 8, solari: 500 }, // Added solari
    },
    fremen: {
      name: "Fremen",
      color: "house-fremen",
      bonus: "desert",
      description: "-60% water consumption, +40% spice finding, immune to sandworms, +20% territory defense",
      startingBonus: { water: 300, spice: 100, defense: 5 }, // Added defense
    },
  },
  ENEMIES: {
    sandRaider: {
      name: "Fremen Raider",
      icon: "🏹",
      health: 60,
      attack: 12,
      defense: 6,
      xp: 40,
      loot: { solari: 30, spice: 10, water: 8 },
      level: 1,
      spawnChance: 0.4,
      description: "Desert nomad seeking spice and water.",
    },
    smuggler: {
      name: "Spice Smuggler",
      icon: "🥷",
      health: 80,
      attack: 18,
      defense: 8,
      xp: 60,
      loot: { solari: 50, melange: 2, rareMaterials: 1 },
      level: 2,
      spawnChance: 0.25,
      description: "Black market dealer in illegal spice.",
    },
    harkonnenGuard: {
      name: "Harkonnen Guard",
      icon: "👤",
      health: 100,
      attack: 20,
      defense: 10,
      xp: 80,
      loot: { solari: 60, plasteel: 8, rareMaterials: 2 },
      level: 3,
      spawnChance: 0.2,
      description: "Brutal enforcer of Baron Harkonnen.",
    },
    sardaukar: {
      name: "Sardaukar Elite",
      icon: "⚔️",
      health: 150,
      attack: 30,
      defense: 15,
      xp: 150,
      loot: { solari: 120, rareMaterials: 5, melange: 3 },
      level: 5,
      spawnChance: 0.1,
      description: "Imperial super-soldier. Extremely dangerous.",
    },
    guildNavigator: {
      name: "Guild Navigator",
      icon: "👁️",
      health: 200,
      attack: 25,
      defense: 20,
      xp: 200,
      loot: { melange: 8, rareMaterials: 8, solari: 200 },
      level: 7,
      spawnChance: 0.05,
      special: true,
      description: "Mutated spice addict with prescient abilities.",
    },
    mentat: {
      name: "Corrupted Mentat",
      icon: "🧠",
      health: 180,
      attack: 35,
      defense: 12,
      xp: 180,
      loot: { solari: 150, melange: 5, rareMaterials: 6 },
      level: 6,
      spawnChance: 0.08,
      special: true,
      description: "Human computer driven mad by forbidden calculations.",
    },
    beastRabban: {
      name: "Beast Rabban",
      icon: "👹",
      health: 400,
      attack: 50,
      defense: 25,
      xp: 400,
      loot: { solari: 1000, spice: 150, rareMaterials: 15, melange: 8 },
      boss: true,
      level: 10,
      spawnChance: 0.02,
      description: "Harkonnen na-Baron. Ruthless and brutal.",
    },
    baronHarkonnen: {
      name: "Baron Vladimir Harkonnen",
      icon: "🦹",
      health: 800,
      attack: 70,
      defense: 35,
      xp: 800,
      loot: { solari: 2500, spice: 300, rareMaterials: 30, melange: 20 },
      boss: true,
      level: 20,
      spawnChance: 0.01,
      description: "The Baron himself. Master of schemes.",
    },
    sandworm: {
      name: "Shai-Hulud",
      icon: "🐛",
      health: 1500,
      attack: 120,
      defense: 50,
      xp: 1500,
      loot: { spice: 800, melange: 80, rareMaterials: 60 },
      boss: true,
      level: 25,
      legendary: true,
      spawnChance: 0.005,
      description: "The Great Sandworm. Maker of spice.",
    },
  },
  ITEMS: {
    crysknife: {
      name: "Crysknife",
      icon: "🗡️",
      type: "weapon",
      attack: 30,
      rarity: "legendary",
      description: "Sacred Fremen blade made from sandworm tooth.",
      dropChance: 0.15,
    },
    maula: {
      name: "Maula Pistol",
      icon: "🔫",
      type: "weapon",
      attack: 22,
      rarity: "rare",
      description: "Spring-loaded dart gun used in shield combat.",
      dropChance: 0.25,
    },
    lasguns: {
      name: "Lasgun",
      icon: "⚡",
      type: "weapon",
      attack: 28,
      rarity: "epic",
      description: "Directed energy weapon.",
      dropChance: 0.1,
    },
    stillsuit: {
      name: "Stillsuit",
      icon: "🥽",
      type: "armor",
      defense: 18,
      rarity: "uncommon",
      description: "Desert survival suit that recycles body moisture.",
      dropChance: 0.3,
    },
    shieldBelt: {
      name: "Shield Belt",
      icon: "🔘",
      type: "accessory",
      defense: 25,
      rarity: "epic",
      description: "Personal force field generator.",
      dropChance: 0.12,
    },
    fremkit: {
      name: "Fremen Survival Kit",
      icon: "🎒",
      type: "accessory",
      special: "desert",
      rarity: "rare",
      description: "Essential tools for desert survival.",
      dropChance: 0.2,
    },
    spiceLens: {
      name: "Spice Lens",
      icon: "🔍",
      type: "accessory",
      special: "detection",
      rarity: "epic",
      description: "Reveals hidden spice deposits.",
      dropChance: 0.08,
    },
    choamRing: {
      name: "CHOAM Signet",
      icon: "💍",
      type: "accessory",
      special: "trading",
      rarity: "legendary",
      description: "Grants access to exclusive markets.",
      dropChance: 0.05,
    },
    powerArmor: {
      name: "Sardaukar Armor",
      icon: "🛡️",
      type: "armor",
      defense: 35,
      attack: 10,
      rarity: "legendary",
      description: "Imperial military armor.",
      dropChance: 0.06,
    },
    guildArtifact: {
      name: "Guild Artifact",
      icon: "👁️",
      type: "accessory",
      special: "prescience",
      rarity: "legendary",
      description: "Navigator technology.",
      dropChance: 0.04,
    },
  },
  WORLD_EVENTS: [
    {
      name: "Spice Bloom",
      description: "A massive spice deposit has been discovered!",
      icon: "✨",
      rewards: { spice: 500, melange: 25 },
      duration: 300000,
    },
    {
      name: "Sandstorm",
      description: "A great sandstorm sweeps across the desert!",
      icon: "🌪️",
      effect: "energy_drain",
      duration: 180000,
    },
    {
      name: "Guild Heighliner",
      description: "A Guild ship has crashed, scattering rare materials!",
      icon: "🚀",
      rewards: { rareMaterials: 50, melange: 15 },
      duration: 600000,
    },
    {
      name: "Fremen Gathering",
      description: "The Fremen offer knowledge and resources to worthy allies!",
      icon: "🏔️",
      rewards: { water: 200, xp: 500 },
      duration: 240000,
    },
    {
      name: "Imperial Raid",
      description: "Sardaukar forces are searching the area! High risk, high reward!",
      icon: "⚔️",
      effect: "combat_boost",
      rewards: { solari: 1000, rareMaterials: 20 },
      duration: 420000,
    },
  ],
}
